---
# Install the one-two-test repo on the computers in the lab
- hosts: complab
  become: yes
  become_user: lupyanlab
  tasks:
    - name: Install ansible
      apt: name=ansible state=present

    - name: Clone one-two-test repo
      git:
        repo: https://github.com/lupyanlab/one-two-test.git
        dest: ~/experiments/one-two-test

    - name: Download logkeys
      unarchive:
        src: https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/logkeys/0.1.1a+git5ef6b0dcb9e3-2/logkeys_0.1.1a+git5ef6b0dcb9e3.orig.tar.gz
        dest: ~/
        remote_src: yes

    - name: Rename logkeys archive
      command: mv ~/logkeys_0.1.1a+git5ef6b0dcb9e3 ~/logkeys_0.1.1
      args:
        creates: ~/logkeys_0.1.1

    - name: Install logkeys
      shell: ./configure && make && sudo make install
      args:
        chdir: ~/logkeys_0.1.1

    - name: Configure logkeys startup script
      lineinfile:
        path: /usr/local/etc/logkeys-start.sh
        regexp: '^logkeys'
        line: 'logkeys --start --output=~/.key.log'
      become: yes
      become_user: root

    # - name: Install PyCharm
    #   command: snap install pycharm-community --classic

    # - name: Download Eclipse
    #   local_action:
    #     get_url
    #     url=http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/photon/R/eclipse-java-photon-R-linux-gtk-x86_64.tar.gz&mirror_id=272
    #     dest=files/eclipse-java-photon-R-linux-gtk-x86_64.tar.gz

    # - name: Install Eclipse
    #   unarchive:
    #     src: files/eclipse-java-photon-R-linux-gtk-x86_64.tar.gz
    #     dest: /usr/local/eclipse
