---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  become_user: "{{ username }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Push all problem repos
      script: scripts/push-all-problem-repos.py
      args:
        chdir: "{{ problems_dir }}"
