---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  become_user: "{{ username }}"
  tasks:
    - name: Turn off keylogger
      command: llkk

    - name: Push all problem repos
      script: scripts/push-all-problem-repos.py
      args:
        chdir: "{{ problems_dir }}"
