---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  become_user: "{{ username }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Clone the problem
      git:
        repo: "{{ problem_repo }}"
        dest: "{{ problem_dst }}"
        accept_hostkey: yes
        key_file: "/home/{{ username }}/.ssh/id_rsa"
        version: "{{ problem_branch }}"

    - name: Create a github endpoint
      command: pipenv run python scripts/create-github-endpoint.py --repo "one-two-test-{{ language }}-{{ problem }}-{{ username }}"
      become: yes
      become_user: lupyanlab

    - name: Point problem to new github endpoint
      command: python3 scripts/set-remote-url.py --dest "{{ problem_dst }}" --repo "one-two-test-{{ language }}-{{ problem }}-{{ username }}"
      become: yes
      become_user: "{{ username }}"

    - name: Copy the snapshot script to the user's bin
      template:
        src: snapshot-problem-repo.j2
        dest: "{{ snapshot_script_dst }}"
        owner: "{{ username }}"
        mode: "u+rwx"

    - name: Set cron job to snapshot problem directory every 5 minutes
      cron:
        name: "snapshot {{ problem }}"
        minute: "*/5"
        job: "{{ snapshot_script_dst }}"
        user: "{{ username }}"
