---
# ansible-playbook setup.yml -e '{"username":"jim", "language":"python", "problem":"bowling"}'

- hosts: localhost
  become: yes
  become_user: lupyanlab
  vars_files:
    - vars/participant.yml
  tasks:
    - name: Create a new user for the participant
      user:
        name: "{{ username }}"
        password: "{{ username | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

- hosts: localhost
  become: yes
  become_user: "{{ username }}"
  tasks:
    - name: Set git config
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - { name: "user.name", value: "{{ username }}" }
        - { name: "user.email", value: "exercise.lab.participant@gmail.com" }
        - { name: "core.editor", value: "vim" }

    - name: Clone the problem
      git:
        repo: https://github.com/exercise-lab/{{ problem }}-{{ language }}.git
        dst: ~/Desktop/

    - name: Start keylogger
      command: llk
