---

- hosts: localhost
  become: yes
  vars_files:
    - vars/participant.yml
  tasks:
    - user:
        name: "{{ username }}"
        password: "{{ username | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - file:
        path: "{{ keylog_file }}"
        state: touch

    - template:
        src: "templates/{{ item }}.j2"
        dest: "~/.{{ item }}"
      become_user: "{{ username }}"
      with_items:
        - bash_profile
        - bash_logout
