---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  become_user: lupyanlab
  vars_files:
    - vars/main.yml
  tasks:
    # remove cron jobs
    # ...

    - name: Find Mozilla databases
      find:
        paths: "/home/{{ username }}/.mozilla"
        patterns: "places.sqlite,formhistory.sqlite"
        recurse: "yes"
      register: mozilla_dbs
      become_user: "{{ username }}"

    - name: Touch browser histories dir
      file:
        path: "{{ browser_histories_dir }}"
        state: directory

    - name: Copy Mozilla databases to lupyanlab
      command: cp {{ item.path }} {{ browser_histories_dir }}/{{ username }}-{{ item.path | basename }}
      with_items: "{{ mozilla_dbs.files }}"
      become: yes
      become_user: root

    - name: Get rid of the user without deleting their files
      user:
        name: "{{ username }}"
        state: absent
      become: yes
      become_user: root
